import { useEffect, useState } from "react";
import { Header } from "../components/header";
import SearchForm from "../components/searchForm";
import { Source_Code_Pro } from "next/font/google";
import Spinner from "../components/spinner";
import ReleaseList from "../components/releaseList";
import fetchData from "../src/service";
const martianMono = Source_Code_Pro({ subsets: ["latin"] });

export default function Home () {

    const [releases, setReleases] = useState([]);
    const [error, setError] = useState(null);
    const [loading, setLoading] = useState(false);
    const [pagination, setPagination] = useState({});
    const [searchQuery, setSearchQuery] = useState('');

    useEffect(() => {
        if (searchQuery) {
            setLoading(true);
            setError(null);
            fetchData(searchQuery, setError, setLoading, setPagination, setReleases);
        }
    }, [searchQuery]);
    function getContent (error, loading, releases, pagination, setSearchQuery, searchQuery) {
        if (error !== null) {
            return <p>{error.message}</p>;
        }

        if (releases.length === 0) {
            return null;
        }

        return (
            <ReleaseList
                releases={releases}
                pagination={pagination}
                setSearchQuery={setSearchQuery}
                searchQuery={searchQuery}
            />
        );
    }
    const content = getContent(error, loading, releases, pagination, setSearchQuery, searchQuery);

    return (
        <>
            <header>
                <title>discogs-digger</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </header>

            <main className={martianMono.className + ' bg-neutral-500 text-white font-light '}>
                <Header/>
                <SearchForm
                    setSearchQuery={setSearchQuery}
                    setError={setError}
                />
                <div className="grid  gap-2  p-4">
                    {content}
                </div>
            </main>
        </>
    );
}
